begin : functions.o main.o
	g++ --std=c++11 main.o functions.o -o 161044063
functions.o : functions.cpp
	g++ -c --std=c++11 functions.cpp
main.o : main.cpp
	g++ -c --std=c++11 main.cpp
clean :
	rm *.o 161044063
